services:
  - type: web
    name: vozeia
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: cd vozeia && gunicorn app.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.1
    plan: free 