services:
  - type: web
    name: vozeia
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m app.app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.1
    plan: free 